version: '3.0'
tasks:
  build:
    - docker build --no-cache -t txn-processor:latest .
    - docker run --rm -d --network txn-processor-network --env-file deployment/config/docker.env -p 9999:9999 -it txn-processor:latest
  run:
    - |
      docker compose \
       -f ./deployment/docker/infra.docker-compose.yaml \
       -f ./deployment/docker/app.docker-compose.yaml \
       -f ./deployment/docker/otel.docker-compose.yaml down -v || true
    - |
      docker compose \
       -f ./deployment/docker/infra.docker-compose.yaml \
       -f ./deployment/docker/app.docker-compose.yaml \
       -f ./deployment/docker/otel.docker-compose.yaml build --no-cache
    - |
       docker compose \
         -f ./deployment/docker/infra.docker-compose.yaml \
         -f ./deployment/docker/app.docker-compose.yaml \
         -f ./deployment/docker/otel.docker-compose.yaml up -d

  db:
    - docker exec -it mariadb mariadb -u user -ppassword default
  
  load:
    cmds:
    - |
      curl -s -X POST http://localhost:9999/v1/accounts \
      -H "Content-Type: application/json" \
      -d '{"account_id":1001,"initial_balance":"50000"}' || true
    - |
      curl -s -X POST http://localhost:9999/v1/accounts \
      -H "Content-Type: application/json" \
      -d '{"account_id":1002,"initial_balance":"0"}' || true
    - |
      hey -n 10000 -c 10000 \
      -m POST \
      -H "Content-Type: application/json" \
      -d '{ "source_account_id": 1001, "destination_account_id": 1002, "amount": "1" }' \
      http://localhost:9999/v1/transfers
